/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "Roman_Math_test.check" instead.
 */

#include <check.h>
#include <stdio.h>

#line 1 "Roman_Math_test.check"
#include "Roman_Math.h"

static void verify_from_int(const int input, const char *expected_result)
{
	char *actual_result = convert_to_Roman(input);

	ck_assert_msg(
			strcmp(expected_result, actual_result) == 0,
			"roman from %d:\n expected %s, but got %s",
			input, expected_result, actual_result);
}
static void verify_addition(char *left, char *right, char *expected_result) {
	char *actual_result = Compute_Roman_Math(left, right,'+');
	ck_assert_msg(
			strcmp(expected_result, actual_result) == 0,
			"%s + %s: expected %s, but was %s",
			left, right, expected_result, actual_result);	       
}
static void verify_subtraction(char *minuend, char *subtrahend, char *expected_result) {
	char *actual_result = Compute_Roman_Math(minuend, subtrahend,'-');
	ck_assert_msg(
			strcmp(expected_result, actual_result) == 0,
			"%s - %s: expected %s, but was %s",
			minuend, subtrahend, expected_result, actual_result);	       
}
START_TEST(sum2test)
{
#line 4
    //char ch1;
	//char ch2;
	//char oper;
	char *result;
    char *Expected;
	Expected = "MD";
	//ch1 = 'X';
	//ch2 = 'X';
	//oper = '+';
	//Result = "M";
	//Result = convert_to_Roman(1000);
	//printf("%c",Result);
	//verify_from_int(1500,"MD");
	verify_addition("C", "C", "CC");
	verify_subtraction("MMDCCLXXVII", "DLV", "MMCCXXII");
	
	//fail_unless(Compute_Roman_Math("X","V",'+') == Result, "sum function borkeder");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, sum2test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
